// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmobf2fgngfS5ls5cIgXBh_LB8VL1GSNg',
    appId: '1:849264970147:web:7e423dbf0be2759f32b216',
    messagingSenderId: '849264970147',
    projectId: 'chat-app-1f991',
    authDomain: 'chat-app-1f991.firebaseapp.com',
    storageBucket: 'chat-app-1f991.appspot.com',
    measurementId: 'G-DK0V634GG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNquAE3inIGKhtBh5rYO49N7KF0oY9rpg',
    appId: '1:849264970147:android:9d90c31ed7a3ae8632b216',
    messagingSenderId: '849264970147',
    projectId: 'chat-app-1f991',
    storageBucket: 'chat-app-1f991.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLz-_lbUeaZqR57HtEwkwgfdpwxOvC9PE',
    appId: '1:849264970147:ios:24032e549236741632b216',
    messagingSenderId: '849264970147',
    projectId: 'chat-app-1f991',
    storageBucket: 'chat-app-1f991.appspot.com',
    iosClientId: '849264970147-ic4ps4fefp9hl80vvcon7ne0t7e7af0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
